/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VolunteersFoundRouteImport } from './routes/volunteers-found'
import { Route as VolunteerHistoryRouteImport } from './routes/volunteer-history'
import { Route as VolunteerDashboardRouteImport } from './routes/volunteer-dashboard'
import { Route as VolunteerAssignedRouteImport } from './routes/volunteer-assigned'
import { Route as VoiceSosRouteImport } from './routes/voice-sos'
import { Route as VoiceDetectedRouteImport } from './routes/voice-detected'
import { Route as VoiceAssistantRouteImport } from './routes/voice-assistant'
import { Route as TrafficRouteImport } from './routes/traffic'
import { Route as SosConfirmRouteImport } from './routes/sos-confirm'
import { Route as SmartwatchRouteImport } from './routes/smartwatch'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ShakeSosRouteImport } from './routes/shake-sos'
import { Route as SeverityRouteImport } from './routes/severity'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchingRouteImport } from './routes/searching'
import { Route as SafetyTipsRouteImport } from './routes/safety-tips'
import { Route as RouteNavigationRouteImport } from './routes/route-navigation'
import { Route as RoleRouteImport } from './routes/role'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReachedRouteImport } from './routes/reached'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PowerSosRouteImport } from './routes/power-sos'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfflineSmsRouteImport } from './routes/offline-sms'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotificationPermissionRouteImport } from './routes/notification-permission'
import { Route as NoVolunteerRouteImport } from './routes/no-volunteer'
import { Route as NoResponseRouteImport } from './routes/no-response'
import { Route as NavigateUserRouteImport } from './routes/navigate-user'
import { Route as MedicalProfileRouteImport } from './routes/medical-profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationPermissionRouteImport } from './routes/location-permission'
import { Route as LiveTrackingRouteImport } from './routes/live-tracking'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as IncomingAlertRouteImport } from './routes/incoming-alert'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HelpSupportRouteImport } from './routes/help-support'
import { Route as HelpProvidedRouteImport } from './routes/help-provided'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FamilyTrackingRouteImport } from './routes/family-tracking'
import { Route as FamilyModeRouteImport } from './routes/family-mode'
import { Route as FallDetectionRouteImport } from './routes/fall-detection'
import { Route as ExpandingRadiusRouteImport } from './routes/expanding-radius'
import { Route as EmergencyTypeRouteImport } from './routes/emergency-type'
import { Route as CprRouteImport } from './routes/cpr'
import { Route as ContactsSetupRouteImport } from './routes/contacts-setup'
import { Route as ContactsAlertedRouteImport } from './routes/contacts-alerted'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as CommunityAlertRouteImport } from './routes/community-alert'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as BleedingRouteImport } from './routes/bleeding'
import { Route as AutoSosSentRouteImport } from './routes/auto-sos-sent'
import { Route as AmbulanceRouteImport } from './routes/ambulance'
import { Route as AlternateRouteRouteImport } from './routes/alternate-route'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiHelpRouteImport } from './routes/ai-help'
import { Route as AiGuidanceActiveRouteImport } from './routes/ai-guidance-active'
import { Route as AiFirstAidRouteImport } from './routes/ai-first-aid'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AcceptRequestRouteImport } from './routes/accept-request'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportSosIdRouteImport } from './routes/report.$sosId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteersFoundRoute = VolunteersFoundRouteImport.update({
  id: '/volunteers-found',
  path: '/volunteers-found',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerHistoryRoute = VolunteerHistoryRouteImport.update({
  id: '/volunteer-history',
  path: '/volunteer-history',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerDashboardRoute = VolunteerDashboardRouteImport.update({
  id: '/volunteer-dashboard',
  path: '/volunteer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerAssignedRoute = VolunteerAssignedRouteImport.update({
  id: '/volunteer-assigned',
  path: '/volunteer-assigned',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceSosRoute = VoiceSosRouteImport.update({
  id: '/voice-sos',
  path: '/voice-sos',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceDetectedRoute = VoiceDetectedRouteImport.update({
  id: '/voice-detected',
  path: '/voice-detected',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceAssistantRoute = VoiceAssistantRouteImport.update({
  id: '/voice-assistant',
  path: '/voice-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const SosConfirmRoute = SosConfirmRouteImport.update({
  id: '/sos-confirm',
  path: '/sos-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartwatchRoute = SmartwatchRouteImport.update({
  id: '/smartwatch',
  path: '/smartwatch',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ShakeSosRoute = ShakeSosRouteImport.update({
  id: '/shake-sos',
  path: '/shake-sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SeverityRoute = SeverityRouteImport.update({
  id: '/severity',
  path: '/severity',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchingRoute = SearchingRouteImport.update({
  id: '/searching',
  path: '/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyTipsRoute = SafetyTipsRouteImport.update({
  id: '/safety-tips',
  path: '/safety-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteNavigationRoute = RouteNavigationRouteImport.update({
  id: '/route-navigation',
  path: '/route-navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachedRoute = ReachedRouteImport.update({
  id: '/reached',
  path: '/reached',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerSosRoute = PowerSosRouteImport.update({
  id: '/power-sos',
  path: '/power-sos',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineSmsRoute = OfflineSmsRouteImport.update({
  id: '/offline-sms',
  path: '/offline-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationPermissionRoute = NotificationPermissionRouteImport.update({
  id: '/notification-permission',
  path: '/notification-permission',
  getParentRoute: () => rootRouteImport,
} as any)
const NoVolunteerRoute = NoVolunteerRouteImport.update({
  id: '/no-volunteer',
  path: '/no-volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const NoResponseRoute = NoResponseRouteImport.update({
  id: '/no-response',
  path: '/no-response',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateUserRoute = NavigateUserRouteImport.update({
  id: '/navigate-user',
  path: '/navigate-user',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalProfileRoute = MedicalProfileRouteImport.update({
  id: '/medical-profile',
  path: '/medical-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationPermissionRoute = LocationPermissionRouteImport.update({
  id: '/location-permission',
  path: '/location-permission',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTrackingRoute = LiveTrackingRouteImport.update({
  id: '/live-tracking',
  path: '/live-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomingAlertRoute = IncomingAlertRouteImport.update({
  id: '/incoming-alert',
  path: '/incoming-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSupportRoute = HelpSupportRouteImport.update({
  id: '/help-support',
  path: '/help-support',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpProvidedRoute = HelpProvidedRouteImport.update({
  id: '/help-provided',
  path: '/help-provided',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyTrackingRoute = FamilyTrackingRouteImport.update({
  id: '/family-tracking',
  path: '/family-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyModeRoute = FamilyModeRouteImport.update({
  id: '/family-mode',
  path: '/family-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const FallDetectionRoute = FallDetectionRouteImport.update({
  id: '/fall-detection',
  path: '/fall-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpandingRadiusRoute = ExpandingRadiusRouteImport.update({
  id: '/expanding-radius',
  path: '/expanding-radius',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyTypeRoute = EmergencyTypeRouteImport.update({
  id: '/emergency-type',
  path: '/emergency-type',
  getParentRoute: () => rootRouteImport,
} as any)
const CprRoute = CprRouteImport.update({
  id: '/cpr',
  path: '/cpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsSetupRoute = ContactsSetupRouteImport.update({
  id: '/contacts-setup',
  path: '/contacts-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsAlertedRoute = ContactsAlertedRouteImport.update({
  id: '/contacts-alerted',
  path: '/contacts-alerted',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAlertRoute = CommunityAlertRouteImport.update({
  id: '/community-alert',
  path: '/community-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const BleedingRoute = BleedingRouteImport.update({
  id: '/bleeding',
  path: '/bleeding',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoSosSentRoute = AutoSosSentRouteImport.update({
  id: '/auto-sos-sent',
  path: '/auto-sos-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulanceRoute = AmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternateRouteRoute = AlternateRouteRouteImport.update({
  id: '/alternate-route',
  path: '/alternate-route',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHelpRoute = AiHelpRouteImport.update({
  id: '/ai-help',
  path: '/ai-help',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGuidanceActiveRoute = AiGuidanceActiveRouteImport.update({
  id: '/ai-guidance-active',
  path: '/ai-guidance-active',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFirstAidRoute = AiFirstAidRouteImport.update({
  id: '/ai-first-aid',
  path: '/ai-first-aid',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptRequestRoute = AcceptRequestRouteImport.update({
  id: '/accept-request',
  path: '/accept-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSosIdRoute = ReportSosIdRouteImport.update({
  id: '/report/$sosId',
  path: '/report/$sosId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-request': typeof AcceptRequestRoute
  '/achievements': typeof AchievementsRoute
  '/ai-first-aid': typeof AiFirstAidRoute
  '/ai-guidance-active': typeof AiGuidanceActiveRoute
  '/ai-help': typeof AiHelpRoute
  '/alerts': typeof AlertsRoute
  '/alternate-route': typeof AlternateRouteRoute
  '/ambulance': typeof AmbulanceRoute
  '/auto-sos-sent': typeof AutoSosSentRoute
  '/bleeding': typeof BleedingRoute
  '/chatbot': typeof ChatbotRoute
  '/community-alert': typeof CommunityAlertRoute
  '/completed': typeof CompletedRoute
  '/contacts-alerted': typeof ContactsAlertedRoute
  '/contacts-setup': typeof ContactsSetupRoute
  '/cpr': typeof CprRoute
  '/emergency-type': typeof EmergencyTypeRoute
  '/expanding-radius': typeof ExpandingRadiusRoute
  '/fall-detection': typeof FallDetectionRoute
  '/family-mode': typeof FamilyModeRoute
  '/family-tracking': typeof FamilyTrackingRoute
  '/feedback': typeof FeedbackRoute
  '/heatmap': typeof HeatmapRoute
  '/help': typeof HelpRoute
  '/help-provided': typeof HelpProvidedRoute
  '/help-support': typeof HelpSupportRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/incoming-alert': typeof IncomingAlertRoute
  '/language': typeof LanguageRoute
  '/live-tracking': typeof LiveTrackingRoute
  '/location-permission': typeof LocationPermissionRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/medical-profile': typeof MedicalProfileRoute
  '/navigate-user': typeof NavigateUserRoute
  '/no-response': typeof NoResponseRoute
  '/no-volunteer': typeof NoVolunteerRoute
  '/notification-permission': typeof NotificationPermissionRoute
  '/notifications': typeof NotificationsRoute
  '/offline-sms': typeof OfflineSmsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/power-sos': typeof PowerSosRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reached': typeof ReachedRoute
  '/resources': typeof ResourcesRoute
  '/rewards': typeof RewardsRoute
  '/role': typeof RoleRoute
  '/route-navigation': typeof RouteNavigationRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/searching': typeof SearchingRoute
  '/settings': typeof SettingsRoute
  '/severity': typeof SeverityRoute
  '/shake-sos': typeof ShakeSosRoute
  '/share': typeof ShareRoute
  '/signup': typeof SignupRoute
  '/smartwatch': typeof SmartwatchRoute
  '/sos-confirm': typeof SosConfirmRoute
  '/traffic': typeof TrafficRoute
  '/voice-assistant': typeof VoiceAssistantRoute
  '/voice-detected': typeof VoiceDetectedRoute
  '/voice-sos': typeof VoiceSosRoute
  '/volunteer-assigned': typeof VolunteerAssignedRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/volunteer-history': typeof VolunteerHistoryRoute
  '/volunteers-found': typeof VolunteersFoundRoute
  '/welcome': typeof WelcomeRoute
  '/report/$sosId': typeof ReportSosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-request': typeof AcceptRequestRoute
  '/achievements': typeof AchievementsRoute
  '/ai-first-aid': typeof AiFirstAidRoute
  '/ai-guidance-active': typeof AiGuidanceActiveRoute
  '/ai-help': typeof AiHelpRoute
  '/alerts': typeof AlertsRoute
  '/alternate-route': typeof AlternateRouteRoute
  '/ambulance': typeof AmbulanceRoute
  '/auto-sos-sent': typeof AutoSosSentRoute
  '/bleeding': typeof BleedingRoute
  '/chatbot': typeof ChatbotRoute
  '/community-alert': typeof CommunityAlertRoute
  '/completed': typeof CompletedRoute
  '/contacts-alerted': typeof ContactsAlertedRoute
  '/contacts-setup': typeof ContactsSetupRoute
  '/cpr': typeof CprRoute
  '/emergency-type': typeof EmergencyTypeRoute
  '/expanding-radius': typeof ExpandingRadiusRoute
  '/fall-detection': typeof FallDetectionRoute
  '/family-mode': typeof FamilyModeRoute
  '/family-tracking': typeof FamilyTrackingRoute
  '/feedback': typeof FeedbackRoute
  '/heatmap': typeof HeatmapRoute
  '/help': typeof HelpRoute
  '/help-provided': typeof HelpProvidedRoute
  '/help-support': typeof HelpSupportRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/incoming-alert': typeof IncomingAlertRoute
  '/language': typeof LanguageRoute
  '/live-tracking': typeof LiveTrackingRoute
  '/location-permission': typeof LocationPermissionRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/medical-profile': typeof MedicalProfileRoute
  '/navigate-user': typeof NavigateUserRoute
  '/no-response': typeof NoResponseRoute
  '/no-volunteer': typeof NoVolunteerRoute
  '/notification-permission': typeof NotificationPermissionRoute
  '/notifications': typeof NotificationsRoute
  '/offline-sms': typeof OfflineSmsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/power-sos': typeof PowerSosRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reached': typeof ReachedRoute
  '/resources': typeof ResourcesRoute
  '/rewards': typeof RewardsRoute
  '/role': typeof RoleRoute
  '/route-navigation': typeof RouteNavigationRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/searching': typeof SearchingRoute
  '/settings': typeof SettingsRoute
  '/severity': typeof SeverityRoute
  '/shake-sos': typeof ShakeSosRoute
  '/share': typeof ShareRoute
  '/signup': typeof SignupRoute
  '/smartwatch': typeof SmartwatchRoute
  '/sos-confirm': typeof SosConfirmRoute
  '/traffic': typeof TrafficRoute
  '/voice-assistant': typeof VoiceAssistantRoute
  '/voice-detected': typeof VoiceDetectedRoute
  '/voice-sos': typeof VoiceSosRoute
  '/volunteer-assigned': typeof VolunteerAssignedRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/volunteer-history': typeof VolunteerHistoryRoute
  '/volunteers-found': typeof VolunteersFoundRoute
  '/welcome': typeof WelcomeRoute
  '/report/$sosId': typeof ReportSosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-request': typeof AcceptRequestRoute
  '/achievements': typeof AchievementsRoute
  '/ai-first-aid': typeof AiFirstAidRoute
  '/ai-guidance-active': typeof AiGuidanceActiveRoute
  '/ai-help': typeof AiHelpRoute
  '/alerts': typeof AlertsRoute
  '/alternate-route': typeof AlternateRouteRoute
  '/ambulance': typeof AmbulanceRoute
  '/auto-sos-sent': typeof AutoSosSentRoute
  '/bleeding': typeof BleedingRoute
  '/chatbot': typeof ChatbotRoute
  '/community-alert': typeof CommunityAlertRoute
  '/completed': typeof CompletedRoute
  '/contacts-alerted': typeof ContactsAlertedRoute
  '/contacts-setup': typeof ContactsSetupRoute
  '/cpr': typeof CprRoute
  '/emergency-type': typeof EmergencyTypeRoute
  '/expanding-radius': typeof ExpandingRadiusRoute
  '/fall-detection': typeof FallDetectionRoute
  '/family-mode': typeof FamilyModeRoute
  '/family-tracking': typeof FamilyTrackingRoute
  '/feedback': typeof FeedbackRoute
  '/heatmap': typeof HeatmapRoute
  '/help': typeof HelpRoute
  '/help-provided': typeof HelpProvidedRoute
  '/help-support': typeof HelpSupportRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/hospitals': typeof HospitalsRoute
  '/incoming-alert': typeof IncomingAlertRoute
  '/language': typeof LanguageRoute
  '/live-tracking': typeof LiveTrackingRoute
  '/location-permission': typeof LocationPermissionRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/medical-profile': typeof MedicalProfileRoute
  '/navigate-user': typeof NavigateUserRoute
  '/no-response': typeof NoResponseRoute
  '/no-volunteer': typeof NoVolunteerRoute
  '/notification-permission': typeof NotificationPermissionRoute
  '/notifications': typeof NotificationsRoute
  '/offline-sms': typeof OfflineSmsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/power-sos': typeof PowerSosRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reached': typeof ReachedRoute
  '/resources': typeof ResourcesRoute
  '/rewards': typeof RewardsRoute
  '/role': typeof RoleRoute
  '/route-navigation': typeof RouteNavigationRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/searching': typeof SearchingRoute
  '/settings': typeof SettingsRoute
  '/severity': typeof SeverityRoute
  '/shake-sos': typeof ShakeSosRoute
  '/share': typeof ShareRoute
  '/signup': typeof SignupRoute
  '/smartwatch': typeof SmartwatchRoute
  '/sos-confirm': typeof SosConfirmRoute
  '/traffic': typeof TrafficRoute
  '/voice-assistant': typeof VoiceAssistantRoute
  '/voice-detected': typeof VoiceDetectedRoute
  '/voice-sos': typeof VoiceSosRoute
  '/volunteer-assigned': typeof VolunteerAssignedRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/volunteer-history': typeof VolunteerHistoryRoute
  '/volunteers-found': typeof VolunteersFoundRoute
  '/welcome': typeof WelcomeRoute
  '/report/$sosId': typeof ReportSosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-request'
    | '/achievements'
    | '/ai-first-aid'
    | '/ai-guidance-active'
    | '/ai-help'
    | '/alerts'
    | '/alternate-route'
    | '/ambulance'
    | '/auto-sos-sent'
    | '/bleeding'
    | '/chatbot'
    | '/community-alert'
    | '/completed'
    | '/contacts-alerted'
    | '/contacts-setup'
    | '/cpr'
    | '/emergency-type'
    | '/expanding-radius'
    | '/fall-detection'
    | '/family-mode'
    | '/family-tracking'
    | '/feedback'
    | '/heatmap'
    | '/help'
    | '/help-provided'
    | '/help-support'
    | '/history'
    | '/home'
    | '/hospitals'
    | '/incoming-alert'
    | '/language'
    | '/live-tracking'
    | '/location-permission'
    | '/login'
    | '/map'
    | '/medical-profile'
    | '/navigate-user'
    | '/no-response'
    | '/no-volunteer'
    | '/notification-permission'
    | '/notifications'
    | '/offline-sms'
    | '/onboarding'
    | '/otp'
    | '/power-sos'
    | '/profile'
    | '/progress'
    | '/reached'
    | '/resources'
    | '/rewards'
    | '/role'
    | '/route-navigation'
    | '/safety-tips'
    | '/searching'
    | '/settings'
    | '/severity'
    | '/shake-sos'
    | '/share'
    | '/signup'
    | '/smartwatch'
    | '/sos-confirm'
    | '/traffic'
    | '/voice-assistant'
    | '/voice-detected'
    | '/voice-sos'
    | '/volunteer-assigned'
    | '/volunteer-dashboard'
    | '/volunteer-history'
    | '/volunteers-found'
    | '/welcome'
    | '/report/$sosId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-request'
    | '/achievements'
    | '/ai-first-aid'
    | '/ai-guidance-active'
    | '/ai-help'
    | '/alerts'
    | '/alternate-route'
    | '/ambulance'
    | '/auto-sos-sent'
    | '/bleeding'
    | '/chatbot'
    | '/community-alert'
    | '/completed'
    | '/contacts-alerted'
    | '/contacts-setup'
    | '/cpr'
    | '/emergency-type'
    | '/expanding-radius'
    | '/fall-detection'
    | '/family-mode'
    | '/family-tracking'
    | '/feedback'
    | '/heatmap'
    | '/help'
    | '/help-provided'
    | '/help-support'
    | '/history'
    | '/home'
    | '/hospitals'
    | '/incoming-alert'
    | '/language'
    | '/live-tracking'
    | '/location-permission'
    | '/login'
    | '/map'
    | '/medical-profile'
    | '/navigate-user'
    | '/no-response'
    | '/no-volunteer'
    | '/notification-permission'
    | '/notifications'
    | '/offline-sms'
    | '/onboarding'
    | '/otp'
    | '/power-sos'
    | '/profile'
    | '/progress'
    | '/reached'
    | '/resources'
    | '/rewards'
    | '/role'
    | '/route-navigation'
    | '/safety-tips'
    | '/searching'
    | '/settings'
    | '/severity'
    | '/shake-sos'
    | '/share'
    | '/signup'
    | '/smartwatch'
    | '/sos-confirm'
    | '/traffic'
    | '/voice-assistant'
    | '/voice-detected'
    | '/voice-sos'
    | '/volunteer-assigned'
    | '/volunteer-dashboard'
    | '/volunteer-history'
    | '/volunteers-found'
    | '/welcome'
    | '/report/$sosId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accept-request'
    | '/achievements'
    | '/ai-first-aid'
    | '/ai-guidance-active'
    | '/ai-help'
    | '/alerts'
    | '/alternate-route'
    | '/ambulance'
    | '/auto-sos-sent'
    | '/bleeding'
    | '/chatbot'
    | '/community-alert'
    | '/completed'
    | '/contacts-alerted'
    | '/contacts-setup'
    | '/cpr'
    | '/emergency-type'
    | '/expanding-radius'
    | '/fall-detection'
    | '/family-mode'
    | '/family-tracking'
    | '/feedback'
    | '/heatmap'
    | '/help'
    | '/help-provided'
    | '/help-support'
    | '/history'
    | '/home'
    | '/hospitals'
    | '/incoming-alert'
    | '/language'
    | '/live-tracking'
    | '/location-permission'
    | '/login'
    | '/map'
    | '/medical-profile'
    | '/navigate-user'
    | '/no-response'
    | '/no-volunteer'
    | '/notification-permission'
    | '/notifications'
    | '/offline-sms'
    | '/onboarding'
    | '/otp'
    | '/power-sos'
    | '/profile'
    | '/progress'
    | '/reached'
    | '/resources'
    | '/rewards'
    | '/role'
    | '/route-navigation'
    | '/safety-tips'
    | '/searching'
    | '/settings'
    | '/severity'
    | '/shake-sos'
    | '/share'
    | '/signup'
    | '/smartwatch'
    | '/sos-confirm'
    | '/traffic'
    | '/voice-assistant'
    | '/voice-detected'
    | '/voice-sos'
    | '/volunteer-assigned'
    | '/volunteer-dashboard'
    | '/volunteer-history'
    | '/volunteers-found'
    | '/welcome'
    | '/report/$sosId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcceptRequestRoute: typeof AcceptRequestRoute
  AchievementsRoute: typeof AchievementsRoute
  AiFirstAidRoute: typeof AiFirstAidRoute
  AiGuidanceActiveRoute: typeof AiGuidanceActiveRoute
  AiHelpRoute: typeof AiHelpRoute
  AlertsRoute: typeof AlertsRoute
  AlternateRouteRoute: typeof AlternateRouteRoute
  AmbulanceRoute: typeof AmbulanceRoute
  AutoSosSentRoute: typeof AutoSosSentRoute
  BleedingRoute: typeof BleedingRoute
  ChatbotRoute: typeof ChatbotRoute
  CommunityAlertRoute: typeof CommunityAlertRoute
  CompletedRoute: typeof CompletedRoute
  ContactsAlertedRoute: typeof ContactsAlertedRoute
  ContactsSetupRoute: typeof ContactsSetupRoute
  CprRoute: typeof CprRoute
  EmergencyTypeRoute: typeof EmergencyTypeRoute
  ExpandingRadiusRoute: typeof ExpandingRadiusRoute
  FallDetectionRoute: typeof FallDetectionRoute
  FamilyModeRoute: typeof FamilyModeRoute
  FamilyTrackingRoute: typeof FamilyTrackingRoute
  FeedbackRoute: typeof FeedbackRoute
  HeatmapRoute: typeof HeatmapRoute
  HelpRoute: typeof HelpRoute
  HelpProvidedRoute: typeof HelpProvidedRoute
  HelpSupportRoute: typeof HelpSupportRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  HospitalsRoute: typeof HospitalsRoute
  IncomingAlertRoute: typeof IncomingAlertRoute
  LanguageRoute: typeof LanguageRoute
  LiveTrackingRoute: typeof LiveTrackingRoute
  LocationPermissionRoute: typeof LocationPermissionRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MedicalProfileRoute: typeof MedicalProfileRoute
  NavigateUserRoute: typeof NavigateUserRoute
  NoResponseRoute: typeof NoResponseRoute
  NoVolunteerRoute: typeof NoVolunteerRoute
  NotificationPermissionRoute: typeof NotificationPermissionRoute
  NotificationsRoute: typeof NotificationsRoute
  OfflineSmsRoute: typeof OfflineSmsRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  PowerSosRoute: typeof PowerSosRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ReachedRoute: typeof ReachedRoute
  ResourcesRoute: typeof ResourcesRoute
  RewardsRoute: typeof RewardsRoute
  RoleRoute: typeof RoleRoute
  RouteNavigationRoute: typeof RouteNavigationRoute
  SafetyTipsRoute: typeof SafetyTipsRoute
  SearchingRoute: typeof SearchingRoute
  SettingsRoute: typeof SettingsRoute
  SeverityRoute: typeof SeverityRoute
  ShakeSosRoute: typeof ShakeSosRoute
  ShareRoute: typeof ShareRoute
  SignupRoute: typeof SignupRoute
  SmartwatchRoute: typeof SmartwatchRoute
  SosConfirmRoute: typeof SosConfirmRoute
  TrafficRoute: typeof TrafficRoute
  VoiceAssistantRoute: typeof VoiceAssistantRoute
  VoiceDetectedRoute: typeof VoiceDetectedRoute
  VoiceSosRoute: typeof VoiceSosRoute
  VolunteerAssignedRoute: typeof VolunteerAssignedRoute
  VolunteerDashboardRoute: typeof VolunteerDashboardRoute
  VolunteerHistoryRoute: typeof VolunteerHistoryRoute
  VolunteersFoundRoute: typeof VolunteersFoundRoute
  WelcomeRoute: typeof WelcomeRoute
  ReportSosIdRoute: typeof ReportSosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteers-found': {
      id: '/volunteers-found'
      path: '/volunteers-found'
      fullPath: '/volunteers-found'
      preLoaderRoute: typeof VolunteersFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer-history': {
      id: '/volunteer-history'
      path: '/volunteer-history'
      fullPath: '/volunteer-history'
      preLoaderRoute: typeof VolunteerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer-dashboard': {
      id: '/volunteer-dashboard'
      path: '/volunteer-dashboard'
      fullPath: '/volunteer-dashboard'
      preLoaderRoute: typeof VolunteerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer-assigned': {
      id: '/volunteer-assigned'
      path: '/volunteer-assigned'
      fullPath: '/volunteer-assigned'
      preLoaderRoute: typeof VolunteerAssignedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-sos': {
      id: '/voice-sos'
      path: '/voice-sos'
      fullPath: '/voice-sos'
      preLoaderRoute: typeof VoiceSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-detected': {
      id: '/voice-detected'
      path: '/voice-detected'
      fullPath: '/voice-detected'
      preLoaderRoute: typeof VoiceDetectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-assistant': {
      id: '/voice-assistant'
      path: '/voice-assistant'
      fullPath: '/voice-assistant'
      preLoaderRoute: typeof VoiceAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos-confirm': {
      id: '/sos-confirm'
      path: '/sos-confirm'
      fullPath: '/sos-confirm'
      preLoaderRoute: typeof SosConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smartwatch': {
      id: '/smartwatch'
      path: '/smartwatch'
      fullPath: '/smartwatch'
      preLoaderRoute: typeof SmartwatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shake-sos': {
      id: '/shake-sos'
      path: '/shake-sos'
      fullPath: '/shake-sos'
      preLoaderRoute: typeof ShakeSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/severity': {
      id: '/severity'
      path: '/severity'
      fullPath: '/severity'
      preLoaderRoute: typeof SeverityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searching': {
      id: '/searching'
      path: '/searching'
      fullPath: '/searching'
      preLoaderRoute: typeof SearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-tips': {
      id: '/safety-tips'
      path: '/safety-tips'
      fullPath: '/safety-tips'
      preLoaderRoute: typeof SafetyTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-navigation': {
      id: '/route-navigation'
      path: '/route-navigation'
      fullPath: '/route-navigation'
      preLoaderRoute: typeof RouteNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reached': {
      id: '/reached'
      path: '/reached'
      fullPath: '/reached'
      preLoaderRoute: typeof ReachedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-sos': {
      id: '/power-sos'
      path: '/power-sos'
      fullPath: '/power-sos'
      preLoaderRoute: typeof PowerSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline-sms': {
      id: '/offline-sms'
      path: '/offline-sms'
      fullPath: '/offline-sms'
      preLoaderRoute: typeof OfflineSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-permission': {
      id: '/notification-permission'
      path: '/notification-permission'
      fullPath: '/notification-permission'
      preLoaderRoute: typeof NotificationPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-volunteer': {
      id: '/no-volunteer'
      path: '/no-volunteer'
      fullPath: '/no-volunteer'
      preLoaderRoute: typeof NoVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-response': {
      id: '/no-response'
      path: '/no-response'
      fullPath: '/no-response'
      preLoaderRoute: typeof NoResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate-user': {
      id: '/navigate-user'
      path: '/navigate-user'
      fullPath: '/navigate-user'
      preLoaderRoute: typeof NavigateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-profile': {
      id: '/medical-profile'
      path: '/medical-profile'
      fullPath: '/medical-profile'
      preLoaderRoute: typeof MedicalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-permission': {
      id: '/location-permission'
      path: '/location-permission'
      fullPath: '/location-permission'
      preLoaderRoute: typeof LocationPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-tracking': {
      id: '/live-tracking'
      path: '/live-tracking'
      fullPath: '/live-tracking'
      preLoaderRoute: typeof LiveTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoming-alert': {
      id: '/incoming-alert'
      path: '/incoming-alert'
      fullPath: '/incoming-alert'
      preLoaderRoute: typeof IncomingAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-support': {
      id: '/help-support'
      path: '/help-support'
      fullPath: '/help-support'
      preLoaderRoute: typeof HelpSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-provided': {
      id: '/help-provided'
      path: '/help-provided'
      fullPath: '/help-provided'
      preLoaderRoute: typeof HelpProvidedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-tracking': {
      id: '/family-tracking'
      path: '/family-tracking'
      fullPath: '/family-tracking'
      preLoaderRoute: typeof FamilyTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-mode': {
      id: '/family-mode'
      path: '/family-mode'
      fullPath: '/family-mode'
      preLoaderRoute: typeof FamilyModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fall-detection': {
      id: '/fall-detection'
      path: '/fall-detection'
      fullPath: '/fall-detection'
      preLoaderRoute: typeof FallDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expanding-radius': {
      id: '/expanding-radius'
      path: '/expanding-radius'
      fullPath: '/expanding-radius'
      preLoaderRoute: typeof ExpandingRadiusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-type': {
      id: '/emergency-type'
      path: '/emergency-type'
      fullPath: '/emergency-type'
      preLoaderRoute: typeof EmergencyTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpr': {
      id: '/cpr'
      path: '/cpr'
      fullPath: '/cpr'
      preLoaderRoute: typeof CprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts-setup': {
      id: '/contacts-setup'
      path: '/contacts-setup'
      fullPath: '/contacts-setup'
      preLoaderRoute: typeof ContactsSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts-alerted': {
      id: '/contacts-alerted'
      path: '/contacts-alerted'
      fullPath: '/contacts-alerted'
      preLoaderRoute: typeof ContactsAlertedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-alert': {
      id: '/community-alert'
      path: '/community-alert'
      fullPath: '/community-alert'
      preLoaderRoute: typeof CommunityAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bleeding': {
      id: '/bleeding'
      path: '/bleeding'
      fullPath: '/bleeding'
      preLoaderRoute: typeof BleedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-sos-sent': {
      id: '/auto-sos-sent'
      path: '/auto-sos-sent'
      fullPath: '/auto-sos-sent'
      preLoaderRoute: typeof AutoSosSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance': {
      id: '/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof AmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternate-route': {
      id: '/alternate-route'
      path: '/alternate-route'
      fullPath: '/alternate-route'
      preLoaderRoute: typeof AlternateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-help': {
      id: '/ai-help'
      path: '/ai-help'
      fullPath: '/ai-help'
      preLoaderRoute: typeof AiHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-guidance-active': {
      id: '/ai-guidance-active'
      path: '/ai-guidance-active'
      fullPath: '/ai-guidance-active'
      preLoaderRoute: typeof AiGuidanceActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-first-aid': {
      id: '/ai-first-aid'
      path: '/ai-first-aid'
      fullPath: '/ai-first-aid'
      preLoaderRoute: typeof AiFirstAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-request': {
      id: '/accept-request'
      path: '/accept-request'
      fullPath: '/accept-request'
      preLoaderRoute: typeof AcceptRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$sosId': {
      id: '/report/$sosId'
      path: '/report/$sosId'
      fullPath: '/report/$sosId'
      preLoaderRoute: typeof ReportSosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcceptRequestRoute: AcceptRequestRoute,
  AchievementsRoute: AchievementsRoute,
  AiFirstAidRoute: AiFirstAidRoute,
  AiGuidanceActiveRoute: AiGuidanceActiveRoute,
  AiHelpRoute: AiHelpRoute,
  AlertsRoute: AlertsRoute,
  AlternateRouteRoute: AlternateRouteRoute,
  AmbulanceRoute: AmbulanceRoute,
  AutoSosSentRoute: AutoSosSentRoute,
  BleedingRoute: BleedingRoute,
  ChatbotRoute: ChatbotRoute,
  CommunityAlertRoute: CommunityAlertRoute,
  CompletedRoute: CompletedRoute,
  ContactsAlertedRoute: ContactsAlertedRoute,
  ContactsSetupRoute: ContactsSetupRoute,
  CprRoute: CprRoute,
  EmergencyTypeRoute: EmergencyTypeRoute,
  ExpandingRadiusRoute: ExpandingRadiusRoute,
  FallDetectionRoute: FallDetectionRoute,
  FamilyModeRoute: FamilyModeRoute,
  FamilyTrackingRoute: FamilyTrackingRoute,
  FeedbackRoute: FeedbackRoute,
  HeatmapRoute: HeatmapRoute,
  HelpRoute: HelpRoute,
  HelpProvidedRoute: HelpProvidedRoute,
  HelpSupportRoute: HelpSupportRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  HospitalsRoute: HospitalsRoute,
  IncomingAlertRoute: IncomingAlertRoute,
  LanguageRoute: LanguageRoute,
  LiveTrackingRoute: LiveTrackingRoute,
  LocationPermissionRoute: LocationPermissionRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MedicalProfileRoute: MedicalProfileRoute,
  NavigateUserRoute: NavigateUserRoute,
  NoResponseRoute: NoResponseRoute,
  NoVolunteerRoute: NoVolunteerRoute,
  NotificationPermissionRoute: NotificationPermissionRoute,
  NotificationsRoute: NotificationsRoute,
  OfflineSmsRoute: OfflineSmsRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  PowerSosRoute: PowerSosRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ReachedRoute: ReachedRoute,
  ResourcesRoute: ResourcesRoute,
  RewardsRoute: RewardsRoute,
  RoleRoute: RoleRoute,
  RouteNavigationRoute: RouteNavigationRoute,
  SafetyTipsRoute: SafetyTipsRoute,
  SearchingRoute: SearchingRoute,
  SettingsRoute: SettingsRoute,
  SeverityRoute: SeverityRoute,
  ShakeSosRoute: ShakeSosRoute,
  ShareRoute: ShareRoute,
  SignupRoute: SignupRoute,
  SmartwatchRoute: SmartwatchRoute,
  SosConfirmRoute: SosConfirmRoute,
  TrafficRoute: TrafficRoute,
  VoiceAssistantRoute: VoiceAssistantRoute,
  VoiceDetectedRoute: VoiceDetectedRoute,
  VoiceSosRoute: VoiceSosRoute,
  VolunteerAssignedRoute: VolunteerAssignedRoute,
  VolunteerDashboardRoute: VolunteerDashboardRoute,
  VolunteerHistoryRoute: VolunteerHistoryRoute,
  VolunteersFoundRoute: VolunteersFoundRoute,
  WelcomeRoute: WelcomeRoute,
  ReportSosIdRoute: ReportSosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
